### ISSUE TITLE
"get git user.name" problem [ST3] in OS Windows

### ISSUE THREAD

**Issue by cryol** [shiyanhui/FileHeader#24]
Hello!
I would like to give your attention to the fact that the method of **subprocess.getstatusoutput ()** - 
does not work in **OS Windows**.

An alternative implementation I apply.

```python
def getstatusoutput(cmd):
    """Return (status, output) of executing cmd in a shell."""
    """This new implementation should work on all platforms."""
    import subprocess
    pipe = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True, universal_newlines=True)
    output = "".join(pipe.stdout.readlines())
    sts = pipe.returncode
    if sts is None: sts = 0
    return sts, output

**Comment by DevNIX** [comment]
Yeah, works for me! :D

Just added that function and modified FileHeader.py to call `getstatusoutput` instead `process.getstatusoutput`.

On function `def get_user()` I had to change this lines
```python
if status == 0 and output:
    user = output
```
to this
```python
if status == 0 and output:
    user = output.rstrip('\n')
```
because the command `git config --get user.name` adds a new line in the end of the string, and that gets writted on the header.

Maybe we should make a pull request?

**Comment by twn346** [comment]
Holy hell you guys are awesome. I was getting *so* frustrated with this.  

This is a confirmed issue on Mac OSX El Capitan v 10.11.3 as well. Both the original issue, and the \n issue mentioned by DevNIX.  
  
I definitely think one of you should submit a pull request for this. For now, at least we know how to fix it.

**Comment by twn346** [comment]
One thing that I might suggest to "kill two birds with one stone" is to simply change 
      `output = "".join(pipe.stdout.readlines())`
to 
     `output = "".join(pipe.stdout.read().splitlines())`

This handles getting rid of the trailing newline for me on OSX El Cap.
