### ISSUE TITLE
Feature: Add FileHeader to Command Palette

### ISSUE THREAD

**Issue by zx8** [shiyanhui/FileHeader#30]
As someone who likes to minimise use of the mouse when coding, I think it'd be useful to be able to access the right-click menu options from the Command Palette (i.e. http://i.imgur.com/h6uSj3F.png), so I can do the following:

* Super+P (command palette pops up)
* type in "FileH..." (options show up)
* select what I want to do (new file, add header etc.)

I realise there are already keybinds that I can use that come with FileHeader out of the box, but since I currently already use the Command Palette extensively for other addons, it saves me having to memorise even more keybinds and just remember "Super+P".

Thoughts?

**Comment by shiyanhui** [comment]
Added.
