### ISSUE TITLE
Enhancements: Allows 3rd-Party plugin to override some settings

### ISSUE THREAD

**Issue by spywhere** [shiyanhui/FileHeader#31]
### Problem
On a new, empty file, usually FileHeader will add a template to that file based on syntax of the file. This, however, make new file creation conflict with 3rd-party plugins (in my case, Javatar) in which two plugin try to create their own template on the same file. The result ends up with a bunch of templates added to the file. This also apply on specific syntax (based on 3rd-party plugins) not all of them.

### My suggestion
To override the settings, that plugin should set the view's settings called `enable_add_template_to_empty_file` to either `True` or `False` based on how plugin want FileHeader to behave as view's settings did not get set easily in the normal workflow (can be set via console only).

**Comment by shiyanhui** [comment]
Fixed
