### ISSUE TITLE
Variable Path Expansion

### ISSUE THREAD

**Issue by nfarrar** [shiyanhui/FileHeader#40]
It doesn't appear that path name expansion is working in the variables, i.e.:

    // specifying the full path works to templates works
    "custom_template_body_path": "/Users/nfarrar/.local/share/sublime-text/templates/header",
    "custom_template_body_path": "/Users/nfarrar/.local/share/sublime-text/templates/body",

    // but specifying a relative path does not
    // "custom_template_header_path": "~/.local/share/sublime-text/templates/header",
    // "custom_template_header_path": "~/.local/share/sublime-text/templates/header",
    // "custom_template_header_path": "$HOME/.local/share/sublime-text/templates/header",
    // "custom_template_header_path": "$HOME/.local/share/sublime-text/templates/header",

I synchronize my settings across multiple systems and platforms - I don't always have the same username or path to `$HOME`, but I can always keep my templates in the same directory *relative to `$HOME`*. 

The other plugins I use do this - so I assumed it was the default behavior - but after checking through sublime text reference manual - it doesn't appear that they are expanded *by default*.

I found some boilerplate code [here](http://stackoverflow.com/a/16408331/212343) that provides an easy solution to perform cross-platform path expansion with sublime settings.

Any chance this could be added?

**Comment by shiyanhui** [comment]
I will fix this later.

**Comment by twn346** [comment]
I didn't see that this was already posted. The fix is very easy and is posted on my issue. You just need to add one function call to one line.

**Comment by shiyanhui** [comment]
Fixed.
