### ISSUE TITLE
FileHeader for Atom

### ISSUE THREAD

**Issue by guiguan** [shiyanhui/FileHeader#44]
Any chance that you could provide a link to my [FileHeader for Atom](https://github.com/guiguan/file-header) project in your README.md?

I loved your FileHeader for Sublime so much. Now I have migrated to Atom and found out there was no FileHeader. I was very disappointed :(, so I implemented one my own. If you could mention this, I think it could benefit other migrants like myself.

Cheers,
Guan

**Comment by shiyanhui** [comment]
Added :)
