### ISSUE TITLE
customize header for desire extension

### ISSUE THREAD

**Issue by alireza-saberi** [shiyanhui/FileHeader#46]
How can I have a customized header?

**Comment by twn346** [comment]
I'm struggling with this same thing at the moment. It seems like there is *supposed* to be a way to, but the way that is documented doesn't seem to work... I'll update here if I find anything out.

**Comment by twn346** [comment]
Fow now it seems like you can just directly modify the headers in the Packages/FileHeader/template/header directory after you select `Browse Packages ... ` in the Preferences menu.  

This obviously isn't the ideal solution, but the setting in the config file seems to be ignored...

**Comment by twn346** [comment]
I actually managed to find a fix for it not supporting the ~. I'll open another issue.
