### ISSUE TITLE
Custom time string format currently does not work

### ISSUE THREAD

**Issue by twn346** [shiyanhui/FileHeader#48]
Hi,

When using a custom time format string the @Last Modified time: time string is not updated in the file properly. 

In the last version, and I this is true of the current version, the issue is with the way you handle the string with regex. Here is the relevant code: 

inside update_automatically function, starting at line 624:  
    
    elif what == LAST_MODIFIED_TIME:
                    line_pattern = '%s\s*%s.*\n' % (
                        line_header, self.time_pattern())

You call a function to get the regex of the time string. 
This is all well and good, except you can not feasibly have a case for every custom format string. 
You have a few options on how to fix this, but the way that seemed least intrusive to me is the way I have modified my current FileHeader.py file. 

In the below function:  

        def time_pattern(self):
        choice = Settings().get('time_format')
        _ = [0, 1, 2]
        if choice not in _:
            choice = 0

        _ = ['\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}',
             '\d{4}-\d{2}-\d{2}', '\d{2}:\d{2}:\d{2}']
        return _[choice]

If you change this file to match any regex if the custom setting is set, then it will work. For example: 

       def time_pattern(self):

        choice = Settings().get('custom_time_format')
        if choice:
            return '.'
        else:
            choice = Settings().get('time_format')

        _ = [0, 1, 2]
        if choice not in _:
            choice = 0

        _ = ['\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}',
             '\d{4}-\d{2}-\d{2}', '\d{2}:\d{2}:\d{2}']
        return _[choice]

**Comment by twn346** [comment]
To be honest, I am not sure why you are searching for the time string regex anyway. You already match on the regex for Last Modified time:, so this whole discussion is redundant. 

If you change the code inside function `update_automatically` to the following: 

    elif what == LAST_MODIFIED_TIME:
                    # old code
                    # line_pattern = '%s\s*%s.*\n' % (
                        # line_header, self.time_pattern())
                    line_pattern = '%s*.*\n' % (
                        line_header)

It seems to work. Although, you would have to verify that.

**Comment by twn346** [comment]
just FYI, the time format string I am using is:

`"custom_time_format": "%a %b %d, %Y %I:%M:%S %p"`

**Comment by shiyanhui** [comment]
Searching before update is to make sure whether what we will update is existed in template. If it's not, then we will not update it.

**Comment by shiyanhui** [comment]
I have fixed it. Thanks!
