### ISSUE TITLE
Last %> is getting cut off

### ISSUE THREAD

**Issue by coteyr** [shiyanhui/FileHeader#50]
When the template is 

<% # @Author: {{author}} %>
<% # @Date:   {{create_time}} %>
<% # @Last Modified by:   {{last_modified_by}} %>
<% # @Last Modified time: {{last_modified_time}} %>

the output is 

<% # @Author: Robert D. Cotey II <coteyr@coteyr.net> %>
<% # @Date:   2015-12-28 09:06:47 %>
<% # @Last Modified by:   Robert D. Cotey II <coteyr@coteyr.net>
<% # @Last Modified time: 2016-02-29 12:32:08

**Comment by mudoo** [comment]
change the template like this

```
/*!
 *
 * Author:	{{author}} ({{email}})
 * Create:	{{create_time}}
 * Update:	{{last_modified_time}}
 */
```

then output

```
/*!
 *
 * Author:	user (mail@google.com)
 * Create:	2016-03-01 17:33:17
 * Update:	202016-03-02 10:26:00
 */
```

**Comment by coteyr** [comment]
That's no good. I need the trailing  %> and it still gets cut off.  Looks like the changes in 39d6b34d602afacbcc51e5e6d1b58c1823dff2c2 FileHeader.py line 609

**Comment by shiyanhui** [comment]
OK, I'll fix it as soon as possible.
