### ISSUE TITLE
Last_modified_time update not working with custom (or default) time format string

### ISSUE THREAD

**Issue by twn346** [shiyanhui/FileHeader#51]
Ok, this time i'm not sure why. 

Here are my user settings: 

    {
    "custom_template_header_path": "~/code_templates/FileHeader/header/",
    "custom_template_body_path": "~/code_templates/FileHeader/body",

    // For now, we have to set time_format to an invalid selection for
    // auto-update to work with a custom time format string.

    // Set this to match my Vim setup i.e.
    // Sun Oct 04, 2015  03:45PM
    "custom_time_format": "%a %b %d, %Y %I:%M:%S %p",

    "Default": {
        "email": "twn346@mail.missouri.edu"
    },

    "file_suffix_mapping": {
        "as": "ActionScript",
        "scpt": "AppleScript",
        "asp": "ASP",
        "aspx": "ASP",
        "bat": "Batch File",
        "cmd": "Batch File",
        "c": "C",
        "cs": "C#",
        "cpp": "C++",
        "hpp": "C++",
        "clj": "Clojure",
        "css": "CSS",
        "D": "D",
        "erl": "Erlang",
        "go": "Go",
        "groovy": "Groovy",
        "hs": "Haskell",
        "htm": "HTML",
        "html": "HTML",
        "java": "Java",
        "js": "JavaScript",
        "tex": "LaTeX",
        "lsp": "Lisp",
        "lua": "Lua",
        "md": "Markdown",
        "mat": "Matlab",
        "m": "Objective-C",
        "ml": "OCaml",
        "p": "Pascal",
        "pl": "Perl",
        "php": "PHP",
        "py": "Python",
        "R": "R",
        "rst": "RestructuredText",
        "rb": "Ruby",
        "scala": "Scala",
        "sh": "ShellScript",
        "sql": "SQL",
        "tcl": "TCL",
        "txt": "Text",
        "xml": "XML"
    }
    }

It will work correctly when I add the header to the file, but it will not update on save. 
Any thoughts? I can provide more details if you need. Just let me know.

**Comment by twn346** [comment]
In fact, this does not update with the default time format strings either.

**Comment by shiyanhui** [comment]
OK, could you open the console and check whether there is error when you save your file? Thanks.

**Comment by twn346** [comment]
Hi, 
No errors on save.

**Comment by shiyanhui** [comment]
That's weird. And can you show me your template header?

**Comment by kwetter** [comment]
Same issue here. Installed your package last week, worked with standard templates.
Today last_modified_time does not update. No console errors
Mac OSX, Sublime Build 3103

**Comment by kwetter** [comment]
Did some testing:

works with: python .py, perl .pl 
doesn't work with: C++ .Cpp, C .c, Matlab .m, CSS .css

I can test more if you want.

perl & python use "#" for comments, all others that i've tested use "*" for commenting.

**Comment by shiyanhui** [comment]
I think I know where the problem is. I will fix it later. Thank you!

**Comment by shiyanhui** [comment]
Fixed.
