### ISSUE TITLE
File Header includes <?php itself when file already has Php code in it

### ISSUE THREAD

**Issue by ManrajGrover** [shiyanhui/FileHeader#55]
File Header includes <?php itself when file already has Php code in it.

Steps to reproduce:

1. Create a php file and add some php code.
2. Right click on that file in Project Structure and click on "File Header"->"Add Header..".
3. See it add File Header as well as php opening tag in the file.

![screenshot from 2016-03-17 23 19 39](https://cloud.githubusercontent.com/assets/5673050/13855652/7b9e279e-ec97-11e5-9e19-cc4ff659615d.png)

**Comment by shiyanhui** [comment]
Fixed. Thanks.
