### ISSUE TITLE
how to add email address in file header

### ISSUE THREAD

**Issue by woshijpf** [shiyanhui/FileHeader#58]
It's the first time for me to use FileHeader plugin in Sublime Text 3,and  and i just want to modify setting file to add email info in my file header,however i don't know how to set it, even though i have read some details in the default setting file,can some warm heart guys to show me how to add email info or add user defined info into file header when i use the Ctrl+Alt+A shortcut key！Thank you !

**Comment by shiyanhui** [comment]
- [Set your custom header](https://github.com/shiyanhui/FileHeader/blob/master/FileHeader.sublime-settings#L33). And in the header, add variable `{{email}}`.
- Then set your email in settings.

**Comment by woshijpf** [comment]
Thank you for your great advise, and i know how to custom my own file header!

**Comment by shiyanhui** [comment]
:)
