### ISSUE TITLE
"#!/usr/bin/env python" line not created when header added to my .py file

### ISSUE THREAD

**Issue by ceciliawong15** [shiyanhui/FileHeader#68]
The file header extension is working as expected for me except that it is not adding this line as the first line of the header for usage with virtualenv:
# !/usr/bin/env python

thank you!

**Comment by shiyanhui** [comment]
Sounds wired. Does your Python.tmpl file contain `#!/usr/bin/env python`?

**Comment by ceciliawong15** [comment]
hi! I just added the line in my python.templ file in the header folder, but now I am unable to add a header to my files (when I click the option from right-clicking, nothing happens).

**Comment by ceciliawong15** [comment]
this worked! sorry, thought that it would be added automatically based on the readme
