### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by subhrm** [shiyanhui/FileHeader#69]
Hi,

I have installed this package in ST3 on Win7-64Bit , but it's not working.

I have tried with python files (.py ext) but it's not adding any header to neither new nor existing files.

It's also not throwing any error message !

Any suggestion would be appreciated .

Thanks,

**Comment by shiyanhui** [comment]
That's weird. Is it really installed? Did you modify the configure file?

**Comment by zbo09** [comment]
I have the same! I am baffled.

**Comment by fanser** [comment]
I have the same problem too. @zbo09 @subhrm did you fix it ?
