### ISSUE TITLE
[Bug] HTML not support

### ISSUE THREAD

**Issue by Kristinita** [shiyanhui/FileHeader#73]
### 1. Summary

Headers not added in my HTML files.

### 2. Expected behavior

Add headers in `.html` files like `.py`, `.css` or `.js` files.

### 3. Actual behavior

Headers not added in my `.html` files. No output in console.

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install FileHeader use Package Control → I restart Sublime Text → I open any `.html` file, for example, [**Test.html**](https://github.com/Kristinita/Kristinita.github.io/blob/master/Sublime-Text/Test.html) → <kbd>Ctrl+Shift+P</kbd> → `FileHeader: Add Header` → <kbd>Enter</kbd> → header not added for me.

If I open any `.py`, `.css` or `.js` file, FileHeader add headers in my files. I use default Sublime Text HTML syntax.

I try to change my theme and color scheme, but FileHeader have same behavior.

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by shiyanhui** [comment]
There is no header for .html, there is only body. https://github.com/shiyanhui/FileHeader/blob/master/template/body/HTML.tmpl

**Comment by Kristinita** [comment]
@shiyanhui , maybe we add header? Or you have oppose arguments?

Thanks.

**Comment by shiyanhui** [comment]
@Kristinita So what do you think is ok to add to the header?

**Comment by Kristinita** [comment]
> So what do you think is ok to be added to the header?

Therefore I use FileHeader.

**Comment by shiyanhui** [comment]
@Kristinita I mean, there is no need to add html header. Have you seen something like this in production environment? This is not general.

```
<!-- @Author: xxx -->
<!-- @Email: xxx -->
<!-- @Last modified by: xxx -->
<!-- @Last modified time: xxx -->
```

If you really really need it in `.html`, please set `custom_template_header_path ` which can be seen in the settings.

**Comment by Kristinita** [comment]
All right, I understood. Thank you!
