### ISSUE TITLE
Initially setting up user settings

### ISSUE THREAD

**Issue by richardhutchison** [shiyanhui/FileHeader#74]
Maybe not an issue but something that would be useful in the README. As a relatively new Sublime user I'm not sure how to set up the User settings.

In attempting to copy and paste from the default "FileHeader.sublime-settings" to "FileHeader.sublime-settings - User" and then change/add values in the "Default": { } section I get the error:

> Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages/User/FileHeader.sublime-settings:217:9

It would be very useful to have an example of how to setup the User settings so that those of us who are not familiar with Jinja2 or Sublime could still setup and use this awesome plugin.

Here's an example of what I was trying:

![screen shot 2017-01-24 at 8 39 18 am](https://cloud.githubusercontent.com/assets/22991610/22256766/a1772bf4-e210-11e6-84f7-0773ff45d56b.png)

**Comment by shiyanhui** [comment]
There's nothing to do with FileHeader. It's about Sublime. The setting is just a json. Read the document of sublime to be familar with it.

**Comment by richardhutchison** [comment]
So, I figured it out. I still think it would be helpful to include a screenshot of how to do it.
I would happily put it together (I already did for myself anyways).

Let me know if I could help with that.

Thanks
